package org.ivcode.secretfilter.authconverter;

import org.springframework.security.authentication.AbstractAuthenticationToken;
import org.springframework.security.oauth2.jwt.Jwt;
import org.springframework.security.oauth2.server.resource.authentication.JwtAuthenticationConverter;
import org.springframework.core.convert.converter.Converter;

/**
 * A convenience class that returns the supported authentication converters
 * 
 * @author isaiah
 *
 */
public class AuthenticationConverters {

	/**
	 * Creates the authentication converter for Keycloak. This converter will parse
	 * the scopes and roles from a Jwt access token generated by Keycloaks
	 * implementation of OpenId Connect.
	 * 
	 * @return The keycloak
	 */
	public static Converter<Jwt, AbstractAuthenticationToken> keycloak() {
		JwtAuthenticationConverter converter = new JwtAuthenticationConverter();
		converter.setJwtGrantedAuthoritiesConverter(new KeycloakGrantedAuthoritiesConverter());

		return converter;
	}
}
